### ISSUE TITLE
Some specific details to add to script

### ISSUE THREAD

**Issue by benlikethecolor** [bagreen/Clue#7]
As of now the user has no idea what user to log into next, so we need to add somewhere so they know what room is next

Some of the passwords might want to be changed, but this won't be long/major

Also might want to add more hints?

We should also probably have a better introduction than the want I wrote (looking at you Jodi)

**Comment by benlikethecolor** [comment]
I added a way for the users to know what room is next, I added text at the bottom of each file saying "the next room is ...."

**Comment by rosemaryearends** [comment]
No longer needed: script contains clues as to the next room and added detail
